services:
  - type: web
    name: quarkus-tarefas
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: QUARKUS_DATASOURCE_DB_KIND
      - key: QUARKUS_DATASOURCE_USERNAME
      - key: QUARKUS_DATASOURCE_PASSWORD
      - key: QUARKUS_DATASOURCE_JDBC_URL
      - key: QUARKUS_HTTP_PORT